import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const Fonts = {
  FontFamily: {
    FredokaCondensedBold: 'Fredoka_Condensed-Bold',
    FredokaCondensedLight: 'Fredoka_Condensed-Light',
    FredokaCondensedMedium: 'Fredoka_Condensed-Medium',
    FredokaCondensedRegular: 'Fredoka_Condensed-Regular',
    FredokaCondensedSemiBold: 'Fredoka_Condensed-SemiBold',
    FredokaExpandedBold: 'Fredoka_Expanded-Bold',
    FredokaExpandedLight: 'Fredoka_Expanded-Light',
    FredokaExpandedMedium: 'Fredoka_Expanded-Medium',
    FredokaExpandedRegular: 'Fredoka_Expanded-Regular',
    FredokaExpandedSemiBold: 'Fredoka_Expanded-SemiBold',
    FredokaSemiCondensedBold: 'Fredoka_SemiCondensed-Bold',
    FredokaSemiCondensedLight: 'Fredoka_SemiCondensed-Light',
    FredokaSemiCondensedMedium: 'Fredoka_SemiCondensed-Medium',
    FredokaSemiCondensedRegular: 'Fredoka_SemiCondensed-Regular',
    FredokaSemiCondensedSemiBold: 'Fredoka_SemiCondensed-SemiBold',
    FredokaSemiExpandedBold: 'Fredoka_SemiExpanded-Bold',
    FredokaSemiExpandedLight: 'Fredoka_SemiExpanded-Light',
    FredokaSemiExpandedMedium: 'Fredoka_SemiExpanded-Medium',
    FredokaSemiExpandedRegular: 'Fredoka_SemiExpanded-Regular',
    FredokaSemiExpandedSemiBold: 'Fredoka_SemiExpanded-SemiBold',
    FredokaBold: 'Fredoka-Bold',
    FredokaLight: 'Fredoka-Light',
    FredokaMedium: 'Fredoka-Medium',
    FredokaRegular: 'Fredoka-Regular',
    FredokaSemiBold: 'Fredoka-SemiBold',
  },
  FontSize: {
    SIZE_1: wp(1),
    SIZE_2: wp(2),
    SIZE_3: wp(3),
    SIZE_4: wp(4),
    SIZE_5: wp(5),
    SIZE_6: wp(6),
    SIZE_7: wp(7),
    SIZE_8: wp(8),
    SIZE_9: wp(9),
    SIZE_10: wp(10),
    SIZE_11: wp(11),
    SIZE_12: wp(12),
    SIZE_13: wp(13),
    SIZE_14: wp(14),
    SIZE_15: wp(15),
  },
};
